list_of_companies = [
    '0982024 BC Ltd',
    '1101664 BC Ltd',
    '1239583 BC Ltd',
    'AKP Services Ltd.',
    'AVS WINDOWS LTD.',
    'Ajit Framing Ltd',
    'Ampere Electrical Ltd.',
    'Ashoka Indian Cuisine',
    "Ashoka Indian Restaurant"
    "Aaron's Restaurant",
    'BG Acupuncture Inc',
    'BULLET EXPRESS INC.',
    'Best Western Plus',
    "Birmingham's Vodka & Ale House",
    "Birmingham's Vodka & Ale House",
    'Blackapple Cellular Ltd',
    'Blue Pacific Drywall Ltd.',
    'CHURCHBRIDGE GAS, RESTAURANT AND CONVENIENCE STORE',
    'Caraway Grill',
    'Choice Enterprises Inc',
    'Circle K',
    'Coach Holdings Inc.',
    'Coquitlam Dairy Distribution Inc',
    'Earls Restaurant Chilliwack',
    'Edge Drywall Ltd',
    'Escalade Transportation Inc',
    'Euro Asia Transload Inc',
    'FRIENDS CONVENIENCE STORE',
    "Frankie's Italian Kitchen & Bar",
    'Friendly Construction Ltd',
    'G star truck repair Ltd',
    'Guru Truck Driving School',
    'Intact Immigration Services Ltd.',
    'JAS AUTO REPAIRS LTD',
    'M Brar Trucking Corporation ',
    'MADEWELL CEDAR INC',
    'New Millenium Tire Center Ltd',
    'PBW Development Ltd',
    'Pace Processing and product development ltd.',
    'Pizza Depot',
    'Prairie Donair Saskatoon Downtown Inc.',
    'Raiwal Agro Tech Foods Ltd',
    'Robins Nest Motel & Cafe',
    'Rolaas Drywall Construction Ltd',
    'Saluki transport',
    'Sandhu Express Inc',
    'Shandhar Hut',
    'Sondh Transport LTD.',
    'Spice Hut',
    'Spices of Punjab',
    'Star anise grill-indian bistro ltd',
    'Taste of India',
    'The Thirsty Scholar',
    'Trendsetter Framing Limited',
    'Vancity Cabinets Ltd',
    'Veerji Fish & Grill Ltd.',
    'Venus Trucking Inc',
    'Vertu Investments Ltd',
    'Virdi Construction Ltd',
    'Zaika Tastes of India Ltd'
]
