list_of_companies = [
                     "1101664 BC Ltd",
                     "Birmingham's Vodka & Ale House",
                     "Ashoka Indian Cuisine",
                     "Sondh Transport LTD.",
                     "AVS WINDOWS LTD.",
                     "1239583 BC Ltd",
                     "Virdi Construction Ltd",
                     "M Brar Trucking Corporation ",
                     "Guru Truck Driving School",
                     "Sandhu Express Inc",
                     "The Thirsty Scholar",
                     "Blue Pacific Drywall Ltd.",
                     "Zaika Tastes of India Ltd",
                     "AKP Services Ltd.",
                     "Star anise grill-indian bistro ltd",
                     "Frankie's Italian Kitchen & Bar",
                     "Earls Restaurant Chilliwack",
                     "Taste of India",
                     "Rolaas Drywall Construction Ltd",
                     "Veerji Fish & Grill Ltd.",
                     "Euro Asia Transload Inc",
                     "Friendly Construction Ltd",
                     "BULLET EXPRESS INC.",
                     "G star truck repair Ltd",
                     "Ajit Framing Ltd",
                     "Venus Trucking Inc",
                     "Pace Processing and product development ltd.",
                     "Blackapple Cellular Ltd",
                     "Choice Enterprises Inc",
                     "Pizza Depot",
                     "Spice Hut",
                     "Spices of Punjab",
                     "Ashoka Indian Restaurant"
                     "Aaron's Restaurant",
                     "Edge Drywall Ltd",
                     "CHURCHBRIDGE GAS, RESTAURANT AND CONVENIENCE STORE",
                     "New Millenium Tire Center Ltd",
                     "MADEWELL CEDAR INC",
                     "Shandhar Hut",
                     "Caraway Grill",
                     "Birmingham's Vodka & Ale House",
                     "Robins Nest Motel & Cafe",
                     "Coquitlam Dairy Distribution Inc",
                     "Escalade Transportation Inc",
                     "Best Western Plus",
                     "Vancity Cabinets Ltd",
                     "JAS AUTO REPAIRS LTD",
                     "Vertu Investments Ltd",
                     "Prairie Donair Saskatoon Downtown Inc.",
                     "Coach Holdings Inc.",
                     "BG Acupuncture Inc",
                     "FRIENDS CONVENIENCE STORE",
                     "Circle K",
                     "Intact Immigration Services Ltd.",
                     "Pizza Depot",
                     "0982024 BC Ltd",
                     "Saluki transport",
                     "PBW Development Ltd",
                     "Raiwal Agro Tech Foods Ltd",
                     "Ampere Electrical Ltd.",
                     "Trendsetter Framing Limited"
]